name: Enforce Branch Protection

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  protect-main:
    runs-on: ubuntu-latest

    steps:
      - name: Ensure gh CLI installed
        uses: cli/gh-action@v2

      - name: Apply branch protection with required reviews
        env:
          GH_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
        run: |
          gh api --method PUT /repos/${{ github.repository }}/branches/main/protection \
            -H "Accept: application/vnd.github+json" \
            -f required_status_checks.strict=true \
            -f enforce_admins=true \
            -f required_pull_request_reviews.dismiss_stale_reviews=true \
            -f required_pull_request_reviews.required_approving_review_count=1 \
            -f required_pull_request_reviews.require_code_owner_reviews=true || echo "⚠️ 보호 실패"

      - name: Log success
        run: echo "✅ 'main' 브랜치에 코드 리뷰 보호 정책 적용 완료"
