---
name: Create .github/workflows Directories

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-directories:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create .github/workflows and subdirectories
        run: |
          mkdir -p .github/workflows/lint
          mkdir -p .github/workflows/security
          mkdir -p .github/workflows/deploy
          mkdir -p .github/workflows/ci
          mkdir -p .github/workflows/utils
          echo "✅ 디렉토리 생성 완료"

      - name: Add dummy .gitkeep to ensure Git tracks empty dirs
        run: |
          find .github/workflows -type d ! -path .github/workflows -exec touch {}/.gitkeep \;
