name: Harden GitHub Repository

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions: write
  security-events: write

jobs:
  setup-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Generate Security Files & Configure Repo
        run: |
          mkdir -p .github
          echo "# Security Policy\n\nPlease report vulnerabilities to [security@example.com](mailto:security@example.com)." > SECURITY.md
          echo "* @your-github-username" > .github/CODEOWNERS

          cat <<EOF > .github/dependabot.yml
          version: 2
          updates:
            - package-ecosystem: "github-actions"
              directory: "/"
              schedule:
                interval: "weekly"
          EOF

          cat <<EOF > .github/codeql.yml
          name: "CodeQL"
          on:
            push:
              branches: ["main"]
            pull_request:
              branches: ["main"]
          jobs:
            analyze:
              name: Analyze
              runs-on: ubuntu-latest
              permissions:
                actions: read
                contents: read
                security-events: write
              strategy:
                matrix:
                  language: [ 'javascript' ]
              steps:
                - uses: actions/checkout@v4
                - uses: github/codeql-action/init@v3
                  with:
                    languages: \${{ matrix.language }}
                - uses: github/codeql-action/analyze@v3
          EOF

      - name: Setup Branch Protection (gh CLI)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPO="${{ github.repository }}"
          gh api -X PUT repos/$REPO/branches/main/protection \
            -f required_status_checks.strict=true \
            -f required_status_checks.contexts='[]' \
            -f enforce_admins=true \
            -f required_pull_request_reviews.dismiss_stale_reviews=true \
            -f required_pull_request_reviews.required_approving_review_count=1 \
            -f restrictions=null

      - name: Enable GitHub Advanced Security
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api -X PATCH repos/${{ github.repository }} \
            -f security_and_analysis.advanced_security.status="enabled"

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(security): add SECURITY.md, CODEOWNERS, dependabot, CodeQL"
          git push
