name: Enable Branch Protection

on:
  workflow_dispatch:

jobs:
  apply-branch-protection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
        run: |
          echo "✅ GH CLI 인증 상태 확인 중..."
          gh auth status

      - name: Apply branch protection rules
        env:
          GH_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
          REPO: davidkims/my_real_study
        run: |
          gh api -X PUT repos/$REPO/branches/main/protection \
            -f required_status_checks.strict=true \
            -f required_status_checks.contexts='[]' \
            -f enforce_admins=true \
            -f required_pull_request_reviews.dismiss_stale_reviews=true \
            -f required_pull_request_reviews.required_approving_review_count=1 \
            -f restrictions=null
