name: Scorecard supply-chain security

on:
  branch_protection_rule:
  schedule:
    - cron: '32 4 * * 1'
  push:
    branches: [ "main" ]

permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch) || github.event_name == 'pull_request'

    permissions:
      security-events: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Run OSSF Scorecard
        uses: ossf/scorecard-action@f49aabe0b5af0936a0987cfb85d86b75731b0186  # v2.4.1
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload SARIF artifact
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1  # v4.6.1
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5

      - name: Upload to GitHub Code Scanning Dashboard
        uses: github/codeql-action/upload-sarif@2b36c681e1e88e5b9f254ec01549d9c2a258c37e  # v3.24.0
        with:
          sarif_file: results.sarif
