name: SonarQube analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK (for Java projects)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=my-project-key
            -Dsonar.projectName=my-project-name
            -Dsonar.projectVersion=1.0
            -Dsonar.sources=src
            -Dsonar.tests=tests
            -Dsonar.language=multi
            -Dsonar.inclusions=**/*.java,**/*.py,**/*.js,**/*.ts,**/*.go,**/*.cs
            -Dsonar.exclusions=**/node_modules/**,**/*.test.*,**/__tests__/**
            -Dsonar.coverage.exclusions=**/test/**,**/*Test.*
            -Dsonar.verbose=true
